# Generated by Django 4.0.5 on 2022-06-21 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recentDeck', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='leagues.deck')),
                ('recentFlavor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='leagues.flavor')),
                ('recentFormat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='leagues.mtgformat')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
