# Generated by Django 4.0.5 on 2022-09-07 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0015_league_tag'),
        ('users', '0002_profile_mtgousername'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='recentTag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='leagues.tag'),
        ),
    ]
