# Generated by Django 4.0.5 on 2022-06-21 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Archetype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Archetype')),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='deck name')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(default='defaultdeck.jpg', upload_to='deckpics')),
                ('archetype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='leagues.archetype')),
            ],
        ),
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='none', max_length=30)),
                ('deck', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='leagues.deck')),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mtgoUserName', models.CharField(max_length=40, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('isFinished', models.BooleanField(default=False, verbose_name='finished')),
            ],
        ),
        migrations.CreateModel(
            name='MtgFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('theirname', models.CharField(max_length=100, null=True)),
                ('game1', models.BooleanField(default=False, help_text='win', verbose_name='Win')),
                ('game2', models.BooleanField(default=False, verbose_name='Win')),
                ('game3', models.BooleanField(default=None, null=True, verbose_name='Win')),
                ('didjawin', models.BooleanField(default=False, verbose_name='Match Win')),
                ('league', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='leagues.league')),
                ('mtgFormat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mtgFormat', to='leagues.mtgformat')),
                ('myDeck', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mydeck', to='leagues.deck')),
                ('myFlavor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mydeckdetails', to='leagues.flavor')),
                ('theirArchetype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='theirarchetype', to='leagues.archetype', verbose_name='Their Archetype')),
                ('theirDeck', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='theirdeck', to='leagues.deck', verbose_name='Their Deck')),
                ('theirFlavor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='theirdetails', to='leagues.flavor', verbose_name='Their Deck Details')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='league',
            name='mtgFormat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mformat', to='leagues.mtgformat'),
        ),
        migrations.AddField(
            model_name='league',
            name='myDeck',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mydeckname', to='leagues.deck'),
        ),
        migrations.AddField(
            model_name='league',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deck',
            name='mtgFormat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='leagues.mtgformat'),
        ),
        migrations.AddField(
            model_name='archetype',
            name='mtgFormat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='leagues.mtgformat'),
        ),
    ]
