# Generated by Django 4.0.5 on 2022-06-30 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archetype',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Archetype'),
        ),
    ]
