# Generated by Django 4.0.5 on 2022-07-02 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0003_flavor_isdefault'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='myFlavor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='myleagueflavor', to='leagues.flavor'),
        ),
    ]
