# Generated by Django 4.0.5 on 2022-08-25 09:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0005_alter_league_date_alter_match_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
