# Generated by Django 4.0.5 on 2022-08-26 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0007_rename_date_league_datecreated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deck',
            old_name='date',
            new_name='dateCreated',
        ),
    ]
