# Generated by Django 4.0.5 on 2022-08-31 20:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0009_rename_date_match_datecreated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='dateCreated',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
