# Generated by Django 4.0.5 on 2022-09-03 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leagues', '0010_alter_match_datecreated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tourneytype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mtgoUserName', models.CharField(max_length=40, null=True)),
                ('dateCreated', models.DateTimeField(default=django.utils.timezone.now)),
                ('isFinished', models.BooleanField(default=False, verbose_name='finished')),
                ('mtgFormat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mformat2', to='leagues.mtgformat')),
                ('myDeck', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mydeckname2', to='leagues.deck')),
                ('myFlavor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='myleagueflavor2', to='leagues.flavor')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
