# Generated by Django 4.0.5 on 2022-09-03 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0011_tourneytype_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='tourneyType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type', to='leagues.tourneytype'),
        ),
    ]
