# Generated by Django 4.0.5 on 2022-09-03 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0012_tournament_tourneytype'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='tourney',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='leagues.tournament'),
        ),
    ]
