# Generated by Django 4.0.5 on 2022-09-07 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0014_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='leagues.tag'),
        ),
    ]
