# Generated by Django 4.0.5 on 2022-09-08 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0016_tag_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='tag',
        ),
        migrations.AddField(
            model_name='league',
            name='tag',
            field=models.ManyToManyField(to='leagues.tag'),
        ),
    ]
