# Generated by Django 4.0.5 on 2022-09-08 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0017_remove_league_tag_league_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='tag',
            field=models.ManyToManyField(related_name='tags', to='leagues.tag'),
        ),
    ]
