# Generated by Django 4.0.5 on 2022-09-09 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0018_alter_league_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='tag',
            field=models.ManyToManyField(related_name='leagues', to='leagues.tag'),
        ),
    ]
