# Generated by Django 4.0.5 on 2022-09-10 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0019_alter_league_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='league',
            old_name='tag',
            new_name='tags',
        ),
    ]
