# Generated by Django 4.0.5 on 2022-11-23 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0023_alter_flavor_deck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='tourney',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='leagues.tournament'),
        ),
    ]
