# Generated by Django 4.0.5 on 2022-12-05 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0026_delete_tourneytype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='archetype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decks', to='leagues.archetype'),
        ),
    ]
